### PR TITLE
changes sonar widget to fill all pixels instead of displaying rays

### PR DESCRIPTION
**Pull request by sbuhmann**
Hi,

I changed the sonar widget to interpolate and fill all pixels within the range instead of displaying rays as it did before. I saw that there were some other changes made in the original repository by fzachert.
I haven't merged these yet.
Sitta

### CODE REVIEW

**Comment by goldhoorn** [comment]
@D-Alex , @fzachert : can you please check this PR i have no sonar anymore and prefer a second opinion.

**Comment by D-Alex** [comment]
I am not using the sonar widget and the original commit was from sbuhmann. Therefore, if it compiles on master I am fine with merging. Maybe @fzachert can check .

**Comment by fzachert** [comment]
The changes don't merge. I tried your changes of the widget without merging, but the widget does not plot any data. I am trying to find out why...

**Comment by goldhoorn** [comment]
@sbuhmann besides the current problems can you rebase against master so i fzachert identifies the problem that it can be merged without conflicts?

**Comment by fzachert** [comment]
Okay, after some happy hours of debugging, the widget is working. I had a signed/unsigned-int-overflow in your widget. If you replace line 56 in the SonarPlot.cc by this it works fine:
 uint index = abs(int((angle-sonarScan.start_bearing).getDeg()/sonarScan.angular_resolution.getDeg()))*sonarScan.number_of_bins + radius;
Otherwise it plots nothing.
The plot looks nice, but it has the scalling problem, I fixed in my commit yesterday. I have a SonarScan with 2000 bins, so the beams do not fit into the window and get cut off.
Can you please fix this, because I do not know how to merge my commits into your new code.

**Comment by goldhoorn** [comment]
Hint @sbuhmann if you give fzachert rights on your repro you can cooperate more easily IN this pull request

**Comment by fzachert** [comment]
I fixed the scalling-problem. If you @sbuhmann give me rights on your repo, I can add the fix to this pull request

**Comment by goldhoorn** [comment]
Then do it and ping here ;)

**Comment by goldhoorn** [comment]
ops thougt you got the rights already

**Comment by sbuhmann** [comment]
Hi,

Sorry for the late response but I haven't been in office last week 
(Astra+Holidays...)
I added fzachert as collaborator. Should I still rebase the repository?

I just pushed a new version to my fork.
Fabio, I added your bugfix for the overflow, however I couldn't 
reproduce the bug. I tried angles up to 180 degrees, up to 2000 bins and 
an angular resolution of 0.5, i.e. 361 beams. Could you send me the meta 
data of your scans, that would help me to do some testing with generated 
data.

I also revised scaling and overlay to work with angles and bins as 
stated above.

Sitta



On 05/06/2015 06:24 PM, Matthias Goldhoorn wrote:
>
> Hint @sbuhmann <https://github.com/sbuhmann> if you give fzachert 
> rights on your repro you can cooperate more easily IN this pull request
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/gui-rock_widget_collection/pull/8#issuecomment-99528722>.
>


-- 

Sitta Buhmann
MARUM
Centre for Marine Environmental Sciences
University of Bremen / Dept. of Geosciences
Leobener Str.
D-28359 Bremen

Phone:  +49 421 218 65613
Fax.:   +49 421 218 9865613
E-Mail: sbuhmann@marum.de
URL:    www.marum.de

**Comment by fzachert** [comment]
Mhm, I think rebasing makes no sense, because my old fix and your new changes do not merge. I think we should go with your new pull request and forget about my old one.

My scan has 256 beams with 2000 bins each, a angular resolution of 0.5 and a start_bearing of -60 degrees.

Have you already pushed your new version to the fork, because I do not see any changes?
If you also revised the scaling problem, I am fine with it. I fixed the scaling too, but we can go with your changes.

Fabio

**Comment by sbuhmann** [comment]
Somehow my last push did not get online. Probably there was an error I 
didn't see. I check that tomorrow.
Sitta

**Comment by sbuhmann** [comment]
Hi Fabio,

this time the push worked. I haven't tested the changes with our real 
sonar data yet, just with some generated.
But I wanted you to get the changes asap to have a look on it.

I still can't reproduce your overflow error even with the parameters you 
gave me.
And wouldn't an angular resolution of 0.5 and a start bearing of -60 
give 241 beams?
Or 256 beams with an angular resolution of 0.5 give a start bearing of 
64 degrees?

With your parameters the overlay has some odd scale numbers now, maybe 
we can work on that.

Sitta


On 05/18/2015 03:37 PM, Fabio Zachert wrote:
>
> Mhm, I think rebasing makes no sense, because my old fix and your new 
> changes do not merge. I think we should go with your new pull request 
> and forget about my old one.
>
> My scan has 256 beams with 2000 bins each, a angular resolution of 0.5 
> and a start_bearing of -60 degrees.
>
> Have you already pushed your new version to the fork, because I do not 
> see any changes?
> If you also revised the scaling problem, I am fine with it. I fixed 
> the scaling too, but we can go with your changes.
>
> Fabio
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/gui-rock_widget_collection/pull/8#issuecomment-103062371>.
>


-- 

Sitta Buhmann
MARUM
Centre for Marine Environmental Sciences
University of Bremen / Dept. of Geosciences
Leobener Str.
D-28359 Bremen

Phone:  +49 421 218 65613
Fax.:   +49 421 218 9865613
E-Mail: sbuhmann@marum.de
URL:    www.marum.de

**Comment by fzachert** [comment]
Hi Sitta,

I tested your commit with my data and it works fine. The scaling works for different number_of_bins.

Sorry, I gave you rounded parameters. My start bearing is -60 with an angular resolution of 120/256 degrees and 256 beams. With these parameters the overlay should have valid scale numbers.

I am fine with merging this pull-request. 
Thanks again, the widget looks pretty good. 

Fabio

**Comment by goldhoorn** [comment]
Sorry this PR seems forgotten, i merge it now

**Pull request merged**
