### PR TITLE
Fixed some c++11 faults

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
constexpr is C++-only. Until we drop C++98 support, better make changes that are both C++11 and C++98-compatible

In this case, doing static const float VAL = constval is not proper C++98 either. One needs to declare the constant in the class and define it in the C++ file.

**Comment by goldhoorn** [comment]
*updated* (with more cleaner implementation)

**Comment by doudou** [comment]
You missed a constexpr in SonarViewGL.h

**Comment by goldhoorn** [comment]
whops sorry *fixed*

**Comment by goldhoorn** [comment]
@doudou pong?

**Pull request merged**
